### ISSUE TITLE
Design the look and feel of the App

### ISSUE THREAD

**Issue by HydroZocker** [MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups#5]

**Comment by doeiit00** [comment]
![Bild_2023-11-25_134605525](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/147036891/2e09d2ef-fa8c-466f-bd99-b62aff73c9bf)

**Comment by doeiit00** [comment]
![image](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/147036891/92e9d745-a0ad-46f1-8964-67e2ba2b0ced)

**Comment by tamoit02** [comment]
![Design Prototyp pdf](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/149052166/c8e62d16-9052-4606-bb05-b8e0bde576ad)

**Comment by tamoit02** [comment]
![Chat_5](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/149052166/2dd967a7-4b25-4198-9ddd-d1ed20ba4850)
![Groupchats_3_1](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/149052166/8c378942-06ff-486e-ab6c-1dcf14f9046e)
![Log In_1](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/149052166/a60a7322-f8df-4198-b9af-482ee0b89d94)
![Normal Chats_3_2](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/149052166/f2939d9b-9dce-41f3-8f14-f3e03bff6c6d)
![Register_2](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/149052166/dcc5ba42-a8a3-4bc4-ae61-e9c3fcaaff5b)
![Settings_4](https://github.com/MaxTrautwein/HS-Esslingen-G3-WS2324-CommunityGroups/assets/149052166/5371a6d5-315e-4439-b988-e09811134698)
